FROM golang:1.24 AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential cmake git && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -ldflags="-s -w" -o /spotter-server ./cmd/server

FROM gcr.io/distroless/base
COPY --from=builder /spotter-server /
ENTRYPOINT ["/spotter-server"]
