services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: spotter
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: spotter
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "35432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spotter -d spotter"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    depends_on:
      - server
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      POI_API_URL: http://server:8080

volumes:
  postgres_data:
